/* * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include "../smart_calc_controller.h"

START_TEST(test_1_incorrect) {
  char *str = "sin(90)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 1.0);
}
END_TEST

START_TEST(test_2_incorrect) {
  char *str = "5-3";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 2.0);
}
END_TEST

START_TEST(test_3_incorrect) {
  char *str = "2*5";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 10.0);
}
END_TEST

START_TEST(test_4_incorrect) {
  char *str = "6/2";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 3.0);
}
END_TEST

START_TEST(test_5_incorrect) {
  char *str = "2^3";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 8.0);
}
END_TEST

START_TEST(test_6_incorrect) {
  char *str = "5mod3";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 2);
}
END_TEST

START_TEST(test_7_incorrect) {
  char *str = ")2+2(";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_8_incorrect) {
  char *str = "2*2(";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_9_incorrect) {
  char *str = "sin()";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_10_incorrect) {
  char *str = "sin(a)";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_11_incorrect) {
  char *str = "2+((((2+2)))";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_12_incorrect) {
  char *str = "2+(2+2)))";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_13_incorrect) {
  char *str = "1.5.5 + 2";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_14_incorrect) {
  char *str = "asin(1)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 90.0);
}
END_TEST

START_TEST(test_15_incorrect) {
  char *str = "acos(0.5)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq(res, 60.0);
}
END_TEST

START_TEST(test_16_incorrect) {
  char *str = "2 + q";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

START_TEST(test_17_incorrect) {
  char *str = "cos(60)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 0.5, 1e-7);
}
END_TEST

START_TEST(test_18_incorrect) {
  char *str = "2+2-3*4+(9/2^3) + sin(90)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, -5.875, 1e-7);
}
END_TEST

START_TEST(test_19_incorrect) {
  char *str = "-(-2)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 2.0, 1e-7);
}
END_TEST

START_TEST(test_20_incorrect) {
  char *str = "ln(2)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 0.693147, 1e-6);
}
END_TEST

START_TEST(test_21_incorrect) {
  char *str = "log(2)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 0.30103, 1e-6);
}
END_TEST

START_TEST(test_22_incorrect) {
  char *str = "sqrt(144)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 12, 1e-6);
}
END_TEST

START_TEST(test_23_incorrect) {
  char *str = "tan(0)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 0.0, 1e-6);
}
END_TEST

START_TEST(test_24_incorrect) {
  char *str = "atan(1)";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 45.0, 1e-6);
}
END_TEST

START_TEST(test_25_incorrect) {
  char *str = "-2+3";
  long double res = 0;
  apiForCalculateStr(str, &res);
  ck_assert_double_eq_tol(res, 1.0, 1e-6);
}
END_TEST

START_TEST(test_26_incorrect) {
  char *str = "sin(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 90);
  ck_assert_double_eq_tol(res, 0.893997, 1e-6);
}
END_TEST

START_TEST(test_27_incorrect) {
  char *str = "cos(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 60);
  ck_assert_double_eq_tol(res, cosl(60), 1e-6);
}
END_TEST

START_TEST(test_28_incorrect) {
  char *str = "tan(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 1);
  ck_assert_double_eq_tol(res, tanl(1), 1e-6);
}
END_TEST

START_TEST(test_29_incorrect) {
  char *str = "asin(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 1);
  ck_assert_double_eq_tol(res, asinl(1), 1e-6);
}
END_TEST

START_TEST(test_30_incorrect) {
  char *str = "acos(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 0.5);
  ck_assert_double_eq_tol(res, acosl(0.5), 1e-6);
}
END_TEST

START_TEST(test_31_incorrect) {
  char *str = "atan(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 1);
  ck_assert_double_eq_tol(res, atanl(1), 1e-6);
}
END_TEST

START_TEST(test_32_incorrect) {
  char *str = "ln(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 2);
  ck_assert_double_eq_tol(res, logl(2), 1e-6);
}
END_TEST

START_TEST(test_33_incorrect) {
  char *str = "log(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 4);
  ck_assert_double_eq_tol(res, log10l(4), 1e-6);
}
END_TEST

START_TEST(test_34_incorrect) {
  char *str = "sqrt(x)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 4);
  ck_assert_double_eq_tol(res, sqrtl(4), 1e-6);
}
END_TEST

START_TEST(test_35_incorrect) {
  char *str = "(-(-x))";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 4);
  ck_assert_double_eq_tol(res, 4, 1e-6);
}
END_TEST

START_TEST(test_36_incorrect) {
  char *str = "x+2*3-(4/2)";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 1);
  ck_assert_double_eq_tol(res, 5.0, 1e-6);
}
END_TEST

START_TEST(test_37_incorrect) {
  char *str = "-x+ 1";
  char *strDivided = lexemsDivider(str);
  char *postfix = fromInfixToPostfix(strDivided);
  free(strDivided);
  long double res = calculateWithX(postfix, 1);
  ck_assert_double_eq_tol(res, 0.0, 1e-6);
}
END_TEST

START_TEST(test_38_incorrect) {
  creditCalcInput inputData;
  inputData.total_loan_amount = "10000";
  inputData.term = "1";
  inputData.interest_rate = "10";
  inputData.type = annuity;

  creditCalcOutput *outputData = apiForCreditCalc(&inputData);
  ck_assert_str_eq(outputData->loan_overpayment, "549.91");
  ck_assert_str_eq(outputData->monthly_payment, "879.16");
  ck_assert_str_eq(outputData->total_repayment, "10549.91");
  freeCreditCalcOutput(outputData);
}
END_TEST

START_TEST(test_39_incorrect) {
  creditCalcInput inputData;
  inputData.total_loan_amount = "10000";
  inputData.term = "1";
  inputData.interest_rate = "10";
  inputData.type = differentiated;

  creditCalcOutput *outputData = apiForCreditCalc(&inputData);
  ck_assert_str_eq(outputData->loan_overpayment, "541.67");
  ck_assert_str_eq(outputData->monthly_payment, "916.67...840.28");
  ck_assert_str_eq(outputData->total_repayment, "10541.67");
  freeCreditCalcOutput(outputData);
}
END_TEST

START_TEST(test_40_incorrect) {
  char *str = "2****2";
  int isValid = isInputValid(str);
  ck_assert_int_eq(isValid, 0);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_1_incorrect);
  tcase_add_test(tc1_1, test_2_incorrect);
  tcase_add_test(tc1_1, test_3_incorrect);
  tcase_add_test(tc1_1, test_4_incorrect);
  tcase_add_test(tc1_1, test_5_incorrect);
  tcase_add_test(tc1_1, test_6_incorrect);
  tcase_add_test(tc1_1, test_7_incorrect);
  tcase_add_test(tc1_1, test_8_incorrect);
  tcase_add_test(tc1_1, test_9_incorrect);
  tcase_add_test(tc1_1, test_10_incorrect);
  tcase_add_test(tc1_1, test_11_incorrect);
  tcase_add_test(tc1_1, test_12_incorrect);
  tcase_add_test(tc1_1, test_13_incorrect);
  tcase_add_test(tc1_1, test_14_incorrect);
  tcase_add_test(tc1_1, test_15_incorrect);
  tcase_add_test(tc1_1, test_16_incorrect);
  tcase_add_test(tc1_1, test_17_incorrect);
  tcase_add_test(tc1_1, test_18_incorrect);
  tcase_add_test(tc1_1, test_19_incorrect);
  tcase_add_test(tc1_1, test_20_incorrect);
  tcase_add_test(tc1_1, test_21_incorrect);
  tcase_add_test(tc1_1, test_22_incorrect);
  tcase_add_test(tc1_1, test_23_incorrect);
  tcase_add_test(tc1_1, test_23_incorrect);
  tcase_add_test(tc1_1, test_23_incorrect);
  tcase_add_test(tc1_1, test_24_incorrect);
  tcase_add_test(tc1_1, test_25_incorrect);
  tcase_add_test(tc1_1, test_26_incorrect);
  tcase_add_test(tc1_1, test_27_incorrect);
  tcase_add_test(tc1_1, test_28_incorrect);
  tcase_add_test(tc1_1, test_29_incorrect);
  tcase_add_test(tc1_1, test_30_incorrect);
  tcase_add_test(tc1_1, test_31_incorrect);
  tcase_add_test(tc1_1, test_32_incorrect);
  tcase_add_test(tc1_1, test_33_incorrect);
  tcase_add_test(tc1_1, test_34_incorrect);
  tcase_add_test(tc1_1, test_35_incorrect);
  tcase_add_test(tc1_1, test_36_incorrect);
  tcase_add_test(tc1_1, test_37_incorrect);
  tcase_add_test(tc1_1, test_38_incorrect);
  tcase_add_test(tc1_1, test_39_incorrect);
  tcase_add_test(tc1_1, test_40_incorrect);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
